# Generated by Django 5.0.4 on 2024-05-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Customer',
        ),
    ]
