# Generated by Django 5.0.4 on 2024-05-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0002_rename_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='vendor_code',
            new_name='vendor_id',
        ),
    ]
